DATA_DIR = "C:/Users/jgtzsx01/Documents/workspace/zjsxzy_in_js/website/everyday-update/data"
STOCK_DIR = "D:/Data/stocks"
INDEX_DIR = "D:/Data/index-component"
BY_STOCK_DIR = "D:/Data/avg_cost/by stock"
BY_DATE_DIR = "D:/Data/avg_cost/by date"
